const appsPortfolio = {
	en: [
		{
			name: 'Company Form - Romania',
			description:
				'Company Form is a simple and effective way to collect company information from your customers.',
			internalUrl: '/apps/company-form-romania',
			externalUrl: 'https://apps.shopify.com/company-form',
			featuredImage: 'company-form-romania',
			isPublic: true,
			isVevolApp: true,
			caseStudy: {
				imagesFolder: 'company-form-romania',
				title: 'Company Form - Romania',
				description:
					'Company Form is a simple and effective way to collect company information from your customers.',
				problem: [
					'Manual CUI validation is time-consuming and error-prone',
					'Businesses struggle with collecting accurate company information for invoicing',
					'No automated way to verify Romanian company details during checkout',
					'Manual data entry leads to invoicing errors and delays',
					'Difficulty in handling VAT registration status for Romanian companies',
					'Lack of standardized company information collection in Shopify stores',
					'Time wasted on verifying company details manually',
					'Risk of incorrect invoicing due to manual data entry',
					'No automated solution for Romanian business-to-business transactions',
					'Complex process of managing company data for multiple orders',
				],
				solution: [
					'Real-time CUI validation and company data retrieval',
					'Automated company information population during checkout',
					'Seamless integration with Shopify checkout process',
					'Instant verification of VAT registration status',
					'Customizable company information form',
					'Automatic cart attribute updates',
					'Flexible theme integration options',
					'Multi-language support for better accessibility',
					'Secure data handling and GDPR compliance',
					'Mutation observer for dynamic cart updates',
				],
				technologies: [
					'Shopify App Bridge',
					'React',
					'GraphQL',
					'Shopify Polaris',
					'Shopify Checkout Extensions API',
					'Shopify Theme App Extensions',
					'Shopify Billing API',
					'Shopify Webhooks',
					'Gadget.dev',
				],
			},
		},
		{
			name: 'Aqurate - Theme App Extension',
			description:
				'Aqurate provides AI-driven personalization tools to boost your eCommerce shop with product recommendations. Our solution integrated with their existent app and provided a native solution in Shopify to display products recommendations in themes ',
			internalUrl: '/apps/aqurate',
			externalUrl: 'https://apps.shopify.com/aqurate-ai',
			featuredImage: 'aqurate',
			isPublic: true,
			isVevolApp: false,
			caseStudy: {
				imagesFolder: 'aqurate',
				title: 'Aqurate - Theme App Extension',
				description:
					'Aqurate provides AI-driven personalization tools to boost your eCommerce shop with product recommendations. Our solution integrated with their existent app and provided a native solution in Shopify to display products recommendations in themes',
				problem: [
					'Slow loading products recommendations after page loading',
					'Add to cart not working in most of the themes',
					'Hardcoded frontend logic caused issues with dynamic product data',
					'Difficulties integrating with Shopify cart functionality without full page reloads',
					'No easy way to inject product recommendations into the cart drawer across themes',
				],
				solution: [
					'Loaded product recommendations in real time using product, customer, and collection metafields, as well as metaobjects for advanced personalization',
					'Multiple Add to Cart solutions that integrate with multiple themes',
					'Built a Theme App Extension to work natively with Online Store 2.0',
					'Refactored frontend code to dynamically adapt to product context and theme context',
					'Used Shopify Ajax API and cart events to enable smooth "Add to Cart" interactions without page reloads for most of the themes',
					'Implemented a Theme App Block that can be easily embedded into the cart drawer to show real-time product recommendations',
				],
				technologies: ['Shopify Metafields', 'Shopify Theme App Extensions'],
			},
		},
		{
			name: 'Addison Lee - Shopify App Integration',
			description:
				'Addison Lee is a leading private hire and courier company. We built a Shopify app integration to enable seamless booking and order management for merchants, connecting their stores with Addison Lee’s logistics platform.',
			internalUrl: '/apps/addison-lee',
			externalUrl: 'https://www.addisonlee.com/',
			featuredImage: 'addison-lee',
			isPublic: true,
			isVevolApp: false,
			caseStudy: {
				imagesFolder: 'addison-lee',
				title: 'Addison Lee - Shopify App Integration',
				description:
					'Addison Lee is a leading private hire and courier company. We built a Shopify app integration to enable seamless booking and order management for merchants, connecting their stores with Addison Lee’s logistics platform.',
				problem: [
					'No direct integration between Shopify and Addison Lee for order fulfillment',
					'Manual booking process for deliveries, leading to errors and delays',
					'Lack of real-time tracking and status updates for merchants and customers',
					'Complexity in managing courier options and pricing within Shopify',
					'Limited automation for order-to-courier workflows',
				],
				solution: [
					'Developed a Shopify app to automate order booking with Addison Lee’s API',
					'Enabled real-time courier availability, pricing, and booking directly from the Shopify admin',
					'Integrated live tracking and status updates for both merchants and customers',
					'Automated order-to-courier assignment, reducing manual work and errors',
					'Provided flexible configuration for delivery options and pricing rules within Shopify',
				],
				technologies: [
					'Shopify Carrier Service API',
					'Shopify Admin API',
					'Shopify Billing API',
					'Shopify Webhooks',
					'Shopify Checkout Extensions API',
					'Shopify Theme App Extensions',
					'Shopify App Bridge',
					'Addison Lee API',
					'React',
					'GraphQL',
					'Shopify Polaris',
					'Gadget.dev',
				],
			},
		},
		{
			name: 'Dispotrading - DispoHub',
			description:
				'A comprehensive business management solution for a Shopify store, providing company management, invoice generation, and customer network features.',
			internalUrl: '/apps/dispotrading',
			externalUrl: '',
			featuredImage: 'dispotrading',
			isPublic: false,
			isVevolApp: false,
			caseStudy: {
				imagesFolder: 'dispotrading',
				title: 'DispoHub - Business Management Solution',
				description:
					'A powerful business management solution that streamlines company management, invoice generation, and customer networking for Shopify stores.',
				problem: [
					'Complex management of company information and legal entities',
					'Manual invoice generation and management',
					'Difficulty in maintaining customer-company relationships',
					'Lack of centralized business information management',
					'Time-consuming customer account management',
					'Challenges in tracking and managing business networks',
					'Manual handling of company verification and validation',
					'Inefficient invoice distribution and tracking',
					'Difficulty in managing multiple company relationships',
					'Lack of automated business data synchronization',
				],
				solution: [
					'Automated company information management system',
					'Integrated invoice generation and tracking',
					'Customer network management and visualization',
					'Centralized business information database',
					'Automated customer account management',
					'Business network relationship tracking',
					'Automated company verification system',
					'Streamlined invoice management and distribution',
					'Multi-company relationship management',
					'Real-time business data synchronization',
				],
				technologies: [
					'React',
					'GraphQL',
					'Shopify Polaris',
					'Shopify Customer Account UI Extensions',
					'Shopify Checkout Extensions API',
					'Shopify Billing API',
					'Shopify Webhooks',
					'Gadget.dev',
					'Shopify Metaobjects API',
				],
			},
		},
	],
	ro: [
		{
			name: 'Company Form - Romania',
			description: 'Colectează și validează CUI-ul persoanelor juridice în timpul procesului de checkout',
			internalUrl: '/ro/proiecte/aplicatii-shopify/validare-cui-romania',
			externalUrl: 'https://apps.shopify.com/company-form',
			featuredImage: 'company-form-romania',
			isPublic: true,
			isVevolApp: true,
			caseStudy: {
				imagesFolder: 'company-form-romania',
				title: 'Company Form - Romania',
				description:
					'Company Form este o modalitate simplă și eficientă de a colecta informații despre persoanele juridice în timpul procesului de checkout',
				problem: [
					'Validarea CUI-ului manual este timp consumat și cu erori',
					'Afacerile își bat capul cu colectarea informațiilor corecte despre persoanele juridice pentru facturare',
					'Nu există o modalitate automată de a verifica detaliile companiilor românești în timpul procesului de checkout',
					'Introducerea manuală de date conduce la erori de facturare și întârzieri',
					'Dificultate în gestionarea statutului de înregistrare a TVA pentru companiile românești',
					'Nu există o modalitate standardizată de a colecta informații despre companiile din magazinul Shopify',
				],
				solution: [
					'Validare CUI în timp real și recuperare de date ale companiilor',
					'Populare automată a informațiilor companiilor în timpul procesului de checkout',
					'Integrare fără probleme cu procesul de checkout Shopify',
					'Verificare instantanee a statutului de înregistrare a TVA',
					'Formular personalizabil de informații despre companie',
					'Actualizări automate ale atributelor coșului de cumpărături',
					'Flexibilitate în opțiunile de integrare a temelor',
					'Suport pentru multiple limbi pentru o mai bună accesibilitate',
					'Gestionare sigură a datelor și conformitate cu GDPR',
					'Observator de mutații pentru actualizări dinamice ale coșului de cumpărături',
				],
				technologies: [
					'Shopify App Bridge',
					'React',
					'GraphQL',
					'Shopify Polaris',
					'Shopify Checkout Extensions API',
					'Shopify Theme App Extensions',
					'Shopify Billing API',
					'Shopify Webhooks',
					'Gadget.dev',
				],
			},
		},
		{
			name: 'Aqurate - Extensie de temă',
			description:
				'Aqurate oferă instrumente de personalizare bazate pe AI pentru a îmbunătăți magazinul dumneavoastră eCommerce cu recomandări de produse. Soluția noastră a fost integrată cu aplicația lor existentă și a furnizat o extensie nativă în Shopify pentru a afișa recomandările de produse în teme',
			internalUrl: '/ro/proiecte/aplicatii-shopify/aqurate',
			externalUrl: 'https://apps.shopify.com/aqurate-ai',
			featuredImage: 'aqurate',
			isPublic: true,
			isVevolApp: false,
			caseStudy: {
				imagesFolder: 'aqurate',
				title: 'Aqurate - Extensie de temă',
				description:
					'Aqurate oferă instrumente de personalizare bazate pe AI pentru a îmbunătăți magazinul dumneavoastră eCommerce cu recomandări de produse. Soluția noastră a fost integrată cu aplicația lor existentă și a furnizat o soluție nativă în Shopify pentru a afișa recomandările de produse în teme',
				problem: [
					'Recomandările de produse se încarcă greu după încărcarea paginii',
					'Adăugarea în coș nu funcționează în majoritatea temelor',
					'Logică codată în față cauzată probleme cu datele produsului dinamic',
					'Dificultăți în integrarea cu funcționalitatea coșului de cumpărături a Shopify fără încărcare completă a paginii',
					'Nu există o modalitate ușoară de a injecta recomandările de produse în coșul de cumpărături în toate temele',
				],
				solution: [
					'Recomandările de produse se încarcă în timp real folosind metafields de produs, client și colecție, precum și metaobjects pentru personalizare avansată',
					'Multiple soluții de adăugare în coș care se integrează cu mai multe teme',
					'Am construit o extensie de temă pentru a lucra nativ cu Online Store 2.0',
					'Refactorizat codul frontend pentru a se adapta dinamic contextului produsului și contextului temei',
					'Folosim API-ul Ajax Shopify și evenimentele coșului de cumpărături pentru a permite interacțiuni "Add to Cart" fără încărcarea completă a paginii pentru majoritatea temelor',
					'Implementat un bloc de temă care poate fi ușor încorporat în coșul de cumpărături pentru a afișa recomandările de produse în timp real',
				],
				technologies: ['Shopify Metafields', 'Shopify Theme App Extensions'],
			},
		},
		{
			name: 'Addison Lee - Integrare aplicație Shopify',
			description:
				'Addison Lee este o companie de transport public și de taxi. Am construit o integrație a aplicației Shopify pentru a permite rezervarea și gestionarea ordinelor fără probleme pentru comercianți, conectând magazinurile lor cu platforma lor de logistică Addison Lee',
			internalUrl: '/ro/proiecte/aplicatii-shopify/addison-lee',
			externalUrl: 'https://www.addisonlee.com/',
			featuredImage: 'addison-lee',
			isPublic: true,
			isVevolApp: false,
			caseStudy: {
				imagesFolder: 'addison-lee',
				title: 'Addison Lee - Integrare aplicație Shopify',
				description:
					'Addison Lee este o companie de transport public și de taxi. Am construit o integrație a aplicației Shopify pentru a permite rezervarea și gestionarea ordinelelor fără probleme pentru comercianți, conectând magazinurile lor cu platforma lor de logistică Addison Lee',
				problem: [
					'Nu există o integrație directă între Shopify și Addison Lee pentru livrare',
					'Procesul manual de rezervare pentru livrări, care duce la erori și întârzieri',
					'Nu există o urmărire în timp real și actualizări de statut pentru comercianți și clienți',
					'Dificultate în gestionarea opțiunilor de transport și a prețurilor în Shopify',
					'Limitare a automatizării pentru fluxurile de lucru de la ordine la curier',
				],
				solution: [
					'Am dezvoltat o aplicație Shopify pentru a automatiza rezervarea de ordine cu API-ul Addison Lee',
					'Am activat disponibilitatea curierilor în timp real, prețurile și rezervarea direct din adminul Shopify',
					'Am integrat urmărirea în timp real și actualizările de statut pentru ambii comercianți și clienți',
					'Am automatizat atribuirea ordinei la curier, reducând munca manuală și erorile',
					'Am furnizat o configurare flexibilă pentru opțiunile de livrare și regulile de preț în Shopify',
				],
				technologies: [
					'Shopify Carrier Service API',
					'Shopify Admin API',
					'Shopify Billing API',
					'Shopify Webhooks',
					'Shopify Checkout Extensions API',
					'Shopify Theme App Extensions',
					'Shopify App Bridge',
					'Addison Lee API',
					'React',
					'GraphQL',
					'Shopify Polaris',
					'Gadget.dev',
				],
			},
		},
		{
			name: 'Dispotrading - DispoHub',
			description:
				'O soluție de management a clienților B2B pentru un magazin Shopify, care oferă funcționalități atât pentru merchant, cât și pentru clienți.',
			internalUrl: '/ro/proiecte/aplicatii-shopify/dispotrading',
			externalUrl: '',
			featuredImage: 'dispotrading',
			isPublic: false,
			isVevolApp: false,
			caseStudy: {
				imagesFolder: 'dispotrading',
				title: 'DispoHub - Soluție de management a afacerilor',
				description:
					'O soluție puternică de management a clienților B2B care simplifică gestionarea companiilor, generarea de facturi și rețeaua de clienți pentru magazinurile Shopify.',
				problem: [
					'Gestionarea complexă a informațiilor companiilor și a entităților legale',
					'Generarea și gestionarea manuală a facturilor',
					'Dificultăți în menținerea relațiilor dintre clienți și companii',
					'Nu există o gestionare centralizată a informațiilor clienților B2B',
					'Gestionarea conturilor clienților este timp consumat',
					'Dificultăți în urmărirea și gestionarea rețelelor clienților B2B',
					'Gestionarea manuală a verificării și validării companiilor',
					'Distribuire și urmărire ineficiente a facturilor',
					'Dificultate în gestionarea relațiilor multiple dintre companii',
					'Nu există o sincronizare automată a datelor clienților B2B',
				],
				solution: [
					'Sistem de gestionare automată a informațiilor companiilor',
					'Integrare a generării și urmăririi facturilor',
					'Gestionare a rețelei de clienți și vizualizare',
					'Bază de date centralizată a informațiilor afacerilor',
					'Gestionare automată a conturilor clienților',
					'Urmărire a relațiilor dintre companii',
					'Sistem de verificare automată a companiilor',
					'Gestionare eficientă a facturilor și distribuției',
					'Gestionare a relațiilor multiple dintre companii',
					'Sincronizare în timp real a datelor clienților B2B',
				],
				technologies: [
					'React',
					'GraphQL',
					'Shopify Polaris',
					'Shopify Customer Account UI Extensions',
					'Shopify Checkout Extensions API',
					'Shopify Billing API',
					'Shopify Webhooks',
					'Gadget.dev',
					'Shopify Metaobjects API',
				],
			},
		},
	],
};

export default appsPortfolio;
