const appsPortfolio = [
	{
		name: 'Company Form - Romania',
		description: 'Company Form is a simple and effective way to collect company information from your customers.',
		internalUrl: '/apps/company-form-romania',
		externalUrl: 'https://apps.shopify.com/company-form',
		featuredImage: 'company-form-romania',
		isPublic: true,
		isVevolApp: true,
		caseStudy: {
			imagesFolder: 'company-form-romania',
			title: 'Company Form - Romania',
			description:
				'Company Form is a simple and effective way to collect company information from your customers.',
			problem: [
				'Manual CUI validation is time-consuming and error-prone',
				'Businesses struggle with collecting accurate company information for invoicing',
				'No automated way to verify Romanian company details during checkout',
				'Manual data entry leads to invoicing errors and delays',
				'Difficulty in handling VAT registration status for Romanian companies',
				'Lack of standardized company information collection in Shopify stores',
				'Time wasted on verifying company details manually',
				'Risk of incorrect invoicing due to manual data entry',
				'No automated solution for Romanian business-to-business transactions',
				'Complex process of managing company data for multiple orders',
			],
			solution: [
				'Real-time CUI validation and company data retrieval',
				'Automated company information population during checkout',
				'Seamless integration with Shopify checkout process',
				'Instant verification of VAT registration status',
				'Customizable company information form',
				'Automatic cart attribute updates',
				'Flexible theme integration options',
				'Multi-language support for better accessibility',
				'Secure data handling and GDPR compliance',
				'Mutation observer for dynamic cart updates',
			],
			technologies: [
				'Shopify App Bridge',
				'React',
				'GraphQL',
				'Shopify Polaris',
				'Shopify Checkout Extensions API',
				'Shopify Theme App Extensions',
				'Shopify Billing API',
				'Shopify Webhooks',
				'Gadget.dev',
			],
		},
	},
	{
		name: 'Aqurate - Theme App Extension',
		description:
			'Aqurate provides AI-driven personalization tools to boost your eCommerce shop with product recommendations. Our solution integrated with their existent app and provided a native solution in Shopify to display products recommendations in themes ',
		internalUrl: '/apps/aqurate',
		externalUrl: 'https://apps.shopify.com/aqurate-ai',
		featuredImage: 'aqurate',
		isPublic: true,
		isVevolApp: false,
		caseStudy: {
			imagesFolder: 'aqurate',
			title: 'Aqurate - Theme App Extension',
			description:
				'Aqurate provides AI-driven personalization tools to boost your eCommerce shop with product recommendations. Our solution integrated with their existent app and provided a native solution in Shopify to display products recommendations in themes',
			problem: [
				'Slow loading products recommendations after page loading',
				'Add to cart not working in most of the themes',
				'Hardcoded frontend logic caused issues with dynamic product data',
				'Difficulties integrating with Shopify cart functionality without full page reloads',
				'No easy way to inject product recommendations into the cart drawer across themes',
			],
			solution: [
				'Loaded product recommendations in real time using product, customer, and collection metafields, as well as metaobjects for advanced personalization',
				'Multiple Add to Cart solutions that integrate with multiple themes',
				'Built a Theme App Extension to work natively with Online Store 2.0',
				'Refactored frontend code to dynamically adapt to product context and theme context',
				'Used Shopify Ajax API and cart events to enable smooth "Add to Cart" interactions without page reloads for most of the themes',
				'Implemented a Theme App Block that can be easily embedded into the cart drawer to show real-time product recommendations',
			],
			technologies: ['Shopify Metafields', 'Shopify Theme App Extensions'],
		},
	},
	{
		name: 'Addison Lee - Shopify App Integration',
		description:
			'Addison Lee is a leading private hire and courier company. We built a Shopify app integration to enable seamless booking and order management for merchants, connecting their stores with Addison Lee’s logistics platform.',
		internalUrl: '/apps/addison-lee',
		externalUrl: 'https://www.addisonlee.com/',
		featuredImage: 'addison-lee',
		isPublic: true,
		isVevolApp: false,
		caseStudy: {
			imagesFolder: 'addison-lee',
			title: 'Addison Lee - Shopify App Integration',
			description:
				'Addison Lee is a leading private hire and courier company. We built a Shopify app integration to enable seamless booking and order management for merchants, connecting their stores with Addison Lee’s logistics platform.',
			problem: [
				'No direct integration between Shopify and Addison Lee for order fulfillment',
				'Manual booking process for deliveries, leading to errors and delays',
				'Lack of real-time tracking and status updates for merchants and customers',
				'Complexity in managing courier options and pricing within Shopify',
				'Limited automation for order-to-courier workflows',
			],
			solution: [
				'Developed a Shopify app to automate order booking with Addison Lee’s API',
				'Enabled real-time courier availability, pricing, and booking directly from the Shopify admin',
				'Integrated live tracking and status updates for both merchants and customers',
				'Automated order-to-courier assignment, reducing manual work and errors',
				'Provided flexible configuration for delivery options and pricing rules within Shopify',
			],
			technologies: [
				'Shopify Carrier Service API',
				'Shopify Admin API',
				'Shopify Billing API',
				'Shopify Webhooks',
				'Shopify Checkout Extensions API',
				'Shopify Theme App Extensions',
				'Shopify App Bridge',
				'Addison Lee API',
				'React',
				'GraphQL',
				'Shopify Polaris',
				'Gadget.dev',
			],
		},
	},
	{
		name: 'Dispotrading - DispoHub',
		description:
			'A comprehensive business management solution for a Shopify store, providing company management, invoice generation, and customer network features.',
		internalUrl: '/apps/dispotrading',
		externalUrl: '',
		featuredImage: 'dispotrading',
		isPublic: false,
		isVevolApp: false,
		caseStudy: {
			imagesFolder: 'dispotrading',
			title: 'DispoHub - Business Management Solution',
			description:
				'A powerful business management solution that streamlines company management, invoice generation, and customer networking for Shopify stores.',
			problem: [
				'Complex management of company information and legal entities',
				'Manual invoice generation and management',
				'Difficulty in maintaining customer-company relationships',
				'Lack of centralized business information management',
				'Time-consuming customer account management',
				'Challenges in tracking and managing business networks',
				'Manual handling of company verification and validation',
				'Inefficient invoice distribution and tracking',
				'Difficulty in managing multiple company relationships',
				'Lack of automated business data synchronization',
			],
			solution: [
				'Automated company information management system',
				'Integrated invoice generation and tracking',
				'Customer network management and visualization',
				'Centralized business information database',
				'Automated customer account management',
				'Business network relationship tracking',
				'Automated company verification system',
				'Streamlined invoice management and distribution',
				'Multi-company relationship management',
				'Real-time business data synchronization',
			],
			technologies: [
				'React',
				'GraphQL',
				'Shopify Polaris',
				'Shopify Customer Account UI Extensions',
				'Shopify Checkout Extensions API',
				'Shopify Billing API',
				'Shopify Webhooks',
				'Gadget.dev',
				'Shopify Metaobjects API',
			],
		},
	},
];

export default appsPortfolio;
