const partnersList = [
	{
		name: 'Seon',
		logo: 'seon',
		intro: 'SEON Fraud Prevention tools help organisations reduce the costs and resources lost to fraud. Spot fake accounts, slash manual reviews and cut chargebacks now.',
		website: 'https://seon.io/',
		tags: ['financial', 'shopify'],
		isUsed: false,
		isTrusted: true,
	},
	{
		name: 'Equivion',
		logo: 'equivion',
		intro: 'At Equivion, they are bookkeepers, payroll and tax specialists, tech advisors, and financial strategists, helping ecommerce businesses thrive.',
		website: 'https://theecommercecpas.com/',
		tags: ['financial', 'shopify'],
		isUsed: false,
		isTrusted: true,
	},
	{
		name: 'Krown Themes',
		logo: 'krown-themes',
		intro: 'Shopify themes for ecommerce store owners who want to attract customers and stand out from the crowd with easy to use and customizable shopify templates.',
		website: 'https://www.krownthemes.com/',
		tags: ['themes', 'shopify'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'Rebuy',
		logo: 'rebuy',
		intro: 'The world’s top brands use Rebuy’s personalization platform to fuel data-driven shopping experiences, win and keep more customers, and accelerate growth.',
		website: 'https://rebuyengine.com/app-store/shopify?ref=744',
		tags: ['conversions', 'shopify'],
		isUsed: false,
		isTrusted: false,
	},
	{
		name: 'Limitless',
		logo: 'limitless-agency',
		intro: 'SEOcupcake & Moloso have merged into Limitless Agency. Digital marketing services integrated with SEO, PPC, Analytics & more. Trafic, conversions & profit.',
		website: 'https://limitless.ro/',
		tags: ['agency', 'marketing'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'Segmentify',
		logo: 'segmentify',
		intro: 'Segmentify is a Customer Engagement Platform, their focus is creating omnichannel personalised experiences for each customer throughout the entire eCommerce journey to increase conversions, engagement, revenue and customer lifetime value.',
		website: 'https://segmentify.com/',
		tags: ['omnichannel', 'conversions'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'SyncSpider',
		logo: 'syncspider',
		intro: 'SyncSpider is an Ipaas solution with a strong focus on eCommerce integrations. It offers highly customizable automation and out-of-the-box workflows.',
		website: 'https://syncspider.com/',
		tags: ['omnichannel'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'ReConvert',
		logo: 'reconvert',
		intro: 'ReConvert helps you sell more, by making it easy to optimize your post-purchase journey. Add checkout upsells, one-click upsells, thank you page offers & more in minutes.',
		website: 'https://www.reconvert.io/',
		tags: ['shopify', 'conversions'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'Klaviyo',
		logo: 'klaviyo',
		intro: 'Targeted, personalized messages powered by all of your customer data - scale your email and SMS marketing efforts.',
		website: 'https://www.klaviyo.com/',
		tags: ['marketing'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'Gorgias',
		logo: 'gorgias',
		intro: 'Centralize all your support tickets in one place and seamlessly integrate with Shopify with Gorgias, an all-in-one tool.',
		website: 'https://www.gorgias.com/',
		tags: ['shopify'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'Applications Studio',
		logo: 'applicationsstudio',
		intro: 'Application studios: Native apps with premium performance for Android and iOS. Build your own mobile and send push notifications, integrate your marketing channels and increase your conversion rate with a no-code drag and drop builder.',
		website: 'https://www.applications.studio/',
		tags: ['omnichannel', 'marketing'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'Rush',
		logo: 'rush',
		intro: 'Rush: Build a beautiful custom tracking page, access all shipments in one dashboard and provide an outstanding post-purchase experience. Integrate with all your marketing channels and passively increase your revenue.',
		website: 'https://www.rush.app/',
		tags: ['shopify'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'Coso.AI',
		logo: 'coso-ai',
		intro: 'Automatically generates engaging social media content for your brand each week, based on your brand’s personality and relevant social trends.',
		website: 'https://coso.ai/',
		tags: ['ai'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'Eyeris',
		logo: 'eyeris',
		intro: 'Create AI-powered product videos and images for your social and ad channels. Better content, less work. No design skills necessary.',
		website: 'https://www.eyeris.io/',
		tags: ['shopify', 'marketing'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'TBM Solution',
		logo: 'tbm-solution',
		intro: 'TBM Solution is the exclusive Irish fulfilment provider for fast, fixed-rate next-day delivery in the UK and Ireland. With hubs in Dublin and Bedfordshire, they offer seamless cross-border trade for startups to established brands. They simplify VAT and customs procedures, providing a seamless experience.',
		website: 'https://www.tbm-solution.com/',
		tags: ['supply chain'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'Amore Digital',
		logo: 'amore-digital',
		intro: 'Amore Digital is a paid ads consultancy with a strong focus on paid media for e-commerce brands. This includes researching, building and managing performance campaigns across Google ads, shopping and meta ads with a strong focus on ROI.',
		website: 'https://www.amoredigital.co.uk/',
		tags: ['marketing'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'eCom Accel Romania',
		logo: 'ecomm-accel',
		intro: "Your e-commerce acceleration program, specially designed to help you develop and grow your success in the online environment in Romania and abroad. Don't have an online store yet? eComm Accel is your start in the world of e-commerce. You'll receive personalized strategies and guidance to build your online business now. Already have an online store and want to grow it? eComm Accel provides the resources and expertise needed for the expansion and optimization of your business.",
		website: 'https://www.amoredigital.co.uk/',
		tags: ['agency', 'omnichannel'],
		isUsed: true,
		isTrusted: true,
	},
];
export default partnersList;
