const partnersList = [
	{
		name: 'Seon',
		logo: 'seon',
		intro: 'SEON Fraud Prevention tools help organisations reduce the costs and resources lost to fraud. Spot fake accounts, slash manual reviews and cut chargebacks now.',
		website: 'https://seon.io/',
		tags: ['financial', 'shopify'],
		isUsed: false,
		isTrusted: true,
	},
	{
		name: 'Videowise',
		logo: 'videowise',
		intro: 'Videowise enhances eCommerce with interactive, shoppable videos, boosting engagement and conversions while offering analytics and automation.',
		website: 'https://videowise.com/',
		tags: ['marketing', 'shopify', 'video', 'conversions'],
		isUsed: false,
		isTrusted: true,
	},
	{
		name: 'Netopia',
		logo: 'netopia',
		intro: 'NETOPIA Payments offers secure, innovative eCommerce and SMS payment solutions with easy integration and reliable service, earning trust industry-wide.',
		website: 'https://netopia-payments.com/',
		tags: ['financial', 'shopify', 'payments'],
		isUsed: false,
		isTrusted: true,
	},
	{
		name: 'Midsummer Agency',
		logo: 'midsummer',
		intro: `Midsummer Agency, based in sunny Sardinia of Italy, boosts brands with PPC, analytics, and CRO, targeting global markets effectively.`,
		website: 'https://midsummer.agency/',
		tags: ['agency', 'marketing'],
		isUsed: false,
		isTrusted: true,
	},
	{
		name: 'Equivion',
		logo: 'equivion',
		intro: 'At Equivion, they are bookkeepers, payroll and tax specialists, tech advisors, and financial strategists, helping ecommerce businesses thrive.',
		website: 'https://theecommercecpas.com/',
		tags: ['financial', 'shopify'],
		isUsed: false,
		isTrusted: true,
	},
	{
		name: 'Krown Themes',
		logo: 'krown-themes',
		intro: 'Shopify themes for ecommerce store owners who want to attract customers and stand out from the crowd with easy to use and customizable shopify templates.',
		website: 'https://www.krownthemes.com/',
		tags: ['themes', 'shopify'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'Rebuy',
		logo: 'rebuy',
		intro: 'The world’s top brands use Rebuy’s personalization platform to fuel data-driven shopping experiences, win and keep more customers, and accelerate growth.',
		website: 'https://rebuyengine.com/app-store/shopify?ref=744',
		tags: ['conversions', 'shopify'],
		isUsed: false,
		isTrusted: false,
	},
	{
		name: 'Limitless',
		logo: 'limitless-agency',
		intro: 'SEOcupcake & Moloso have merged into Limitless Agency. Digital marketing services integrated with SEO, PPC, Analytics & more. Trafic, conversions & profit.',
		website: 'https://limitless.ro/',
		tags: ['agency', 'marketing'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'Segmentify',
		logo: 'segmentify',
		intro: 'Segmentify boosts eCommerce with omnichannel, personalized experiences to increase conversions, engagement, revenue, and customer value.',
		website: 'https://segmentify.com/',
		tags: ['omnichannel', 'conversions'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'SyncSpider',
		logo: 'syncspider',
		intro: 'SyncSpider is an Ipaas solution with a strong focus on eCommerce integrations. It offers highly customizable automation and out-of-the-box workflows.',
		website: 'https://syncspider.com/',
		tags: ['omnichannel'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'ReConvert',
		logo: 'reconvert',
		intro: 'ReConvert optimizes your post-purchase journey with easy checkout upsells, one-click upsells, and thank you page offers to boost sales.',
		website: 'https://www.reconvert.io/',
		tags: ['shopify', 'conversions'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'Klaviyo',
		logo: 'klaviyo',
		intro: 'Targeted, personalized messages powered by all of your customer data - scale your email and SMS marketing efforts.',
		website: 'https://www.klaviyo.com/',
		tags: ['marketing'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'Gorgias',
		logo: 'gorgias',
		intro: 'Centralize all your support tickets in one place and seamlessly integrate with Shopify with Gorgias, an all-in-one tool.',
		website: 'https://www.gorgias.com/',
		tags: ['shopify'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'Applications Studio',
		logo: 'applicationsstudio',
		intro: 'Application studios offer premium native apps for Android and iOS. Build mobile apps and boost conversions with no-code, drag-and-drop tools and integrated marketing.',
		website: 'https://www.applications.studio/',
		tags: ['omnichannel', 'marketing'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'Rush',
		logo: 'rush',
		intro: 'Rush: Create a custom tracking page, manage all shipments from one dashboard, and enhance post-purchase experiences. Boost revenue with integrated marketing.',
		website: 'https://www.rush.app/',
		tags: ['shopify'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'Coso.AI',
		logo: 'coso-ai',
		intro: 'Automatically generates engaging social media content for your brand each week, based on your brand’s personality and relevant social trends.',
		website: 'https://coso.ai/',
		tags: ['ai'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'Eyeris',
		logo: 'eyeris',
		intro: 'Create AI-powered product videos and images for your social and ad channels. Better content, less work. No design skills necessary.',
		website: 'https://www.eyeris.io/',
		tags: ['shopify', 'marketing'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'TBM Solution',
		logo: 'tbm-solution',
		intro: 'TBM Solution, exclusive in Ireland/UK, offers fast, fixed-rate next-day delivery and simplifies VAT/customs for seamless cross-border trade.',
		website: 'https://www.tbm-solution.com/',
		tags: ['supply chain'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'Amore Digital',
		logo: 'amore-digital',
		intro: 'Amore Digital specializes in paid media for e-commerce, managing performance campaigns across Google Ads and Meta with a focus on ROI.',
		website: 'https://www.amoredigital.co.uk/',
		tags: ['marketing'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'eComm Accel Romania',
		logo: 'ecomm-accel',
		intro: 'eComm Accel: Accelerate your e-commerce success in Romania and internationally with personalized strategies and expert guidance. Optimize and expand your online business with eComm Accel.',
		website: 'https://myidea.ro/ecomm-accel/',
		tags: ['agency', 'omnichannel'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'Kimonix',
		logo: 'kimonix',
		intro: 'Kimonix is a profit-driven merchandising platform that enhances sales and optimizes inventory by syncing data points and enabling complex strategies with advanced functionalities.',
		website: 'https://www.kimonix.com/',
		tags: ['shopify', 'omnichannel'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'Downpay: Deposits made simple',
		logo: 'downpay',
		intro: 'Deposits on Shopify made simple. Enable partial payments to increase your online sales for preorders, services, bookings and made to order products. Split payments, easy collection options, and a shopper-centric customer portal.',
		website: 'https://getdownpay.com/',
		tags: ['shopify', 'payments'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'Alia Popup: Story Learn Popups',
		logo: 'alia',
		intro: 'Alia is a popup alternative that lets brands reward shoppers with discounts for learning more about their story and products. This engaging and educational experience results in 2x - 4x more purchases from new site visitors compared to traditional popups. Alia is trusted by top Shopify brands like Firebelly Tea, co-founded by the President of Shopify, MASA Chips, and Bibado.',
		website: 'https://www.alialearn.com/',
		tags: ['shopify', 'conversions'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'Vitra.ai',
		logo: 'vitra',
		intro: 'Vitra.ai empowers global businesses by breaking language barriers. Founded in 2020, Vitra.ai are translation and localization experts who can translate Videos, Images and Websites to 75+ languages with the power of their patented AI engine. Their plug-and-play solution has been a game-changer for enterprise content creation. Vitra.ai are funded by Inflexor vc, 100x VC and Mumbai angels.',
		website: 'https://www.vitra.ai/',
		tags: ['ai'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'Vevol Themes',
		logo: 'vevol-themes',
		intro: "Vevol Themes builds modern and performant Shopify Themes. Aimed at multiple niches, themes are built to ease the merchants' store setup and convert users into customers.",
		website: 'https://www.vevolthemes.com/',
		tags: ['shopify', 'themes'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'Syncio',
		logo: 'syncio',
		intro: 'Real-time sync inventory, products, and orders across multiple Shopify and WooCommerce stores. Seamlessly collaborate with suppliers and sellers, expand your business to new regions and markets, and save hours each week.',
		website: 'https://www.syncio.co/',
		tags: ['shopify', 'ecommerce', 'sync', 'collaboration', 'inventory'],
		isUsed: true,
		isTrusted: true,
	},
	{
		name: 'GiftNote',
		logo: 'giftnote',
		intro: 'Giftnote allows Shopify stores to enable an automated and paperless gift messaging and gift voucher experience that drives new revenue through gifting.',
		website: 'https://giftnote.com/',
		tags: ['shopify', 'gift', 'automation'],
		isUsed: true,
		isTrusted: true,
	},
];
export default partnersList;
